### PR TITLE
added millis option

### PR DESCRIPTION
**Pull request by pranavjha**

### CODE REVIEW

**Comment by senthilp** [comment]
@pranavjha the attribute should be called `delay` which is more appropriate.

**Comment by pranavjha** [comment]
@senthilp `-d` is already used for domains, Will change the attribute name to delay, but the shorthand cannot be `-d`.

**Comment by senthilp** [comment]
@pranavjha we don't need to have a shorthand for `delay`, just the full name would be enough. Lot of CLIs do not have shorthands for every option. All your changes are good, just remove the shorthand reference. Also I have updated the files to follow ES6 guideline as the latest eslint config. Can you please rebase with the latest and then submit a pull request.

**Comment by pranavjha** [comment]
done :+1:

**Pull request closed without merging**
